name: ✨ Publish Release

on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_APP_SLUG: monsieurboutte/jeff-ai
  DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get the tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          tagName: ${{ github.ref_name }}
          command: release draft ${{ env.CN_APP_SLUG }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  build:
    needs: draft
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          # MacOS Intel
          - host: macos-latest
            target: x86_64-apple-darwin
          # MacOS Silicon
          - host: macos-latest
            target: aarch64-apple-darwin
          # Windows
          - host: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4

      - name: Create .env.production file
        shell: bash
        if: runner.os != 'Windows'
        run: |
          touch .env.production
          echo "DEEPGRAM_API_KEY=${{ secrets.DEEPGRAM_API_KEY }}" >> .env.production
          echo "Verifying .env.production content:"
          cat .env.production
          echo "Checking if DEEPGRAM_API_KEY is set in environment:"
          if [ ! -z "$DEEPGRAM_API_KEY" ]; then
            echo "DEEPGRAM_API_KEY is set"
          else
            echo "DEEPGRAM_API_KEY is not set"
          fi

      - name: Create .env.production file (Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          New-Item -Path .env.production -ItemType File -Force
          Add-Content -Path .env.production -Value "DEEPGRAM_API_KEY=${{ secrets.DEEPGRAM_API_KEY }}"
          Write-Output "Verifying .env.production content:"
          Get-Content .env.production
          Write-Output "Checking if DEEPGRAM_API_KEY is set in environment:"
          if ($env:DEEPGRAM_API_KEY) {
            Write-Output "DEEPGRAM_API_KEY is set"
          } else {
            Write-Output "DEEPGRAM_API_KEY is not set"
          }

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - name: Add x86_64-apple-darwin target
        if: matrix.settings.target == 'x86_64-apple-darwin'
        run: rustup target add x86_64-apple-darwin

      - name: build tauri app
        shell: bash
        run: |
          echo "Checking DEEPGRAM_API_KEY before build:"
          if [ ! -z "$DEEPGRAM_API_KEY" ]; then
            echo "DEEPGRAM_API_KEY is set"
          else
            echo "DEEPGRAM_API_KEY is not set"
          fi
          pnpm install
          pnpm run tauri build --ci --target ${{ matrix.settings.target }}
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APP_SLUG }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  publish:
    needs: [draft, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create .env.production file
        shell: bash
        run: |
          touch .env.production
          echo "DEEPGRAM_API_KEY=${{ secrets.DEEPGRAM_API_KEY }}" >> .env.production
          cat .env.production

      - name: publish release
        uses: crabnebula-dev/cloud-release@v0
        with:
          tagName: ${{ github.ref_name }}
          command: release publish ${{ env.CN_APP_SLUG }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}
